import type { fetchCheatleData } from "../hooks/fetchCheatleData";
import { TILES } from "./tiles";

const defaultData: Awaited<ReturnType<typeof fetchCheatleData>> = {
    board: [
        TILES.T, 
        TILES.L, 
        TILES.A, 
        TILES.F, 
        TILES.L, 
        TILES.U, 
        TILES.O, 
        TILES.T, 
        TILES.B, 
        TILES.N, 
        TILES.G, 
        TILES.A, 
        TILES.E, 
        TILES.D, 
        TILES.D, 
        TILES.L
    ],
    validWords: [
        { text: 'LUBED', value: 13 },  
        { text: 'DEBUG', value: 15 },  
        { text: 'GLADDEN', value: 15 },
        { text: 'BULLA', value: 12 },  
        { text: 'TUBED', value: 12 },  
        { text: 'BUNG', value: 12 },   
        { text: 'NEBULA', value: 12 }, 
        { text: 'FOUND', value: 12 },  
        { text: 'DEBUT', value: 12 },  
        { text: 'LAGUNE', value: 12 }, 
        { text: 'BULL', value: 11 },   
        { text: 'AFOUL', value: 11 },  
        { text: 'GULL', value: 11 },   
        { text: 'FAULT', value: 11 },  
        { text: 'BUND', value: 11 },   
        { text: 'BUG', value: 11 },    
        { text: 'NOUGAT', value: 11 }, 
        { text: 'UNGOT', value: 10 },  
        { text: 'LOTA', value: 5 },    
        { text: 'LONG', value: 8 },    
        { text: 'LONE', value: 5 },    
        { text: 'LOG', value: 7 },     
        { text: 'LOAD', value: 7 },    
        { text: 'ALT', value: 4 },     
        { text: 'ALL', value: 5 },     
        { text: 'ALOFT', value: 9 },   
        { text: 'ALONG', value: 9 },   
        { text: 'ALONE', value: 6 },   
        { text: 'TUB', value: 8 },     
        { text: 'AFT', value: 6 },     
        { text: 'ATOLL', value: 7 },   
        { text: 'ATONE', value: 5 },
        { text: 'ATONED', value: 8 },
        { text: 'FALL', value: 9 },
        { text: 'TUN', value: 5 },
        { text: 'FAUN', value: 9 },
        { text: 'FAT', value: 6 },
        { text: 'FATAL', value: 9 },
        { text: 'FOAL', value: 8 },
        { text: 'FOU', value: 8 },
        { text: 'FOUL', value: 10 },
        { text: 'TUNG', value: 9 },
        { text: 'FON', value: 6 },
        { text: 'FOND', value: 9 },
        { text: 'FOG', value: 9 },
        { text: 'UNBE', value: 9 },
        { text: 'LAD', value: 6 },
        { text: 'UNDE', value: 8 },
        { text: 'OAF', value: 6 },
        { text: 'OAT', value: 3 },
        { text: 'OFT', value: 6 },
        { text: 'OUT', value: 5 },
        { text: 'ONE', value: 3 },
        { text: 'TALL', value: 6 },
        { text: 'TALON', value: 6 },
        { text: 'TALONED', value: 10 },
        { text: 'TAU', value: 5 },
        { text: 'TAUT', value: 6 },
        { text: 'TAUON', value: 7 },
        { text: 'TAO', value: 3 },
        { text: 'TOLA', value: 5 },
        { text: 'TOLL', value: 6 },
        { text: 'TOLU', value: 7 },
        { text: 'TOUT', value: 6 },
        { text: 'TON', value: 3 },
        { text: 'TONG', value: 7 },
        { text: 'TONGA', value: 8 },
        { text: 'TONE', value: 4 },
        { text: 'TONED', value: 7 },
        { text: 'TOG', value: 6 },
        { text: 'TOGA', value: 7 },
        { text: 'TOAD', value: 6 },
        { text: 'TAG', value: 6 },
        { text: 'TAD', value: 5 },
        { text: 'BUT', value: 8 },
        { text: 'TUNE', value: 6 },
        { text: 'TUNED', value: 9 },
        { text: 'BUN', value: 8 },
        { text: 'TUG', value: 8 },
        { text: 'LAT', value: 4 },
        { text: 'LUBE', value: 10 },
        { text: 'BEN', value: 6 },
        { text: 'BEND', value: 9 },
        { text: 'BED', value: 8 },
        { text: 'NUT', value: 5 },
        { text: 'NULL', value: 8 },
        { text: 'NUB', value: 8 },
        { text: 'TUBE', value: 9 },
        { text: 'NOT', value: 3 },
        { text: 'NOTA', value: 4 },
        { text: 'NOTAL', value: 6 },
        { text: 'NOG', value: 6 },
        { text: 'NEB', value: 6 },
        { text: 'LUNG', value: 10 },
        { text: 'GUT', value: 8 },
        { text: 'GUL', value: 9 },
        { text: 'LUNE', value: 7 },
        { text: 'GUN', value: 8 },
        { text: 'GOA', value: 6 },
        { text: 'GOAL', value: 8 },
        { text: 'GOAT', value: 7 },
        { text: 'GOUT', value: 9 },
        { text: 'GOT', value: 6 },
        { text: 'GONE', value: 7 },
        { text: 'GOAD', value: 9 },
        { text: 'GNU', value: 8 },
        { text: 'GAOL', value: 8 },
        { text: 'GAT', value: 6 },
        { text: 'GAD', value: 8 },
        { text: 'GAL', value: 7 },
        { text: 'GLAD', value: 10 },
        { text: 'LUG', value: 9 },
        { text: 'AGO', value: 6 },
        { text: 'AGON', value: 7 },
        { text: 'AGONE', value: 8 },
        { text: 'ADD', value: 7 },
        { text: 'ENOL', value: 5 },
        { text: 'ENG', value: 6 },
        { text: 'END', value: 5 },
        { text: 'DEB', value: 8 },
        { text: 'LOAF', value: 8 },
        { text: 'LOFT', value: 8 },
        { text: 'DEN', value: 5 },
        { text: 'DATA', value: 6 },
        { text: 'DATO', value: 6 },
        { text: 'DAG', value: 8 },
        { text: 'DAGO', value: 9 },
        { text: 'DAL', value: 6 },
        { text: 'LAG', value: 7 },
        { text: 'LOUT', value: 7 },
        { text: 'LOT', value: 4 }
    ],
    topWords: new Map([
        [15, [
            { text: 'DEBUG', value: 15, revealedText: '', isGuessed: false },
            { text: 'GLADDEN', value: 15, revealedText: '', isGuessed: false },
        ]],
        [13, [
            { text: 'LUBED', value: 13, revealedText: '', isGuessed: false }
        ]],
        [12, [
            { text: 'BULLA', value: 12, revealedText: '', isGuessed: false },
            { text: 'TUBED', value: 12, revealedText: '', isGuessed: false },
            { text: 'BUNG', value: 12, revealedText: '', isGuessed: false },
            { text: 'NEBULA', value: 12, revealedText: '', isGuessed: false },
            { text: 'FOUND', value: 12, revealedText: '', isGuessed: false },
            { text: 'DEBUT', value: 12, revealedText: '', isGuessed: false },
            { text: 'LAGUNE', value: 12, revealedText: '', isGuessed: false }
        ]],
    ]),
};

export default defaultData;