import type { TileType } from "../schema/CheatleSchema";
import { TILES } from "./tiles";

export const DICE: TileType[][] = [
    [TILES.A, TILES.E, TILES.I, TILES.O, TILES.N, TILES.J],
    [TILES.E, TILES.R, TILES.S, TILES.T, TILES.L, TILES.K],
    [TILES.A, TILES.E, TILES.I, TILES.O, TILES.U, TILES.Q],
    [TILES.N, TILES.R, TILES.S, TILES.T, TILES.A, TILES.X],
    [TILES.E, TILES.L, TILES.I, TILES.O, TILES.N, TILES.Z],
    [TILES.A, TILES.E, TILES.R, TILES.S, TILES.T, TILES.F],
    [TILES.I, TILES.O, TILES.N, TILES.L, TILES.U, TILES.V],
    [TILES.A, TILES.E, TILES.I, TILES.O, TILES.N, TILES.W],
    [TILES.R, TILES.S, TILES.T, TILES.L, TILES.U, TILES.Y],
    [TILES.A, TILES.E, TILES.I, TILES.O, TILES.N, TILES.M],
    [TILES.E, TILES.R, TILES.S, TILES.T, TILES.L, TILES.P],
    [TILES.A, TILES.E, TILES.I, TILES.O, TILES.U, TILES.C],
    [TILES.N, TILES.R, TILES.S, TILES.T, TILES.A, TILES.G],
    [TILES.E, TILES.L, TILES.I, TILES.O, TILES.N, TILES.H],
    [TILES.A, TILES.E, TILES.R, TILES.S, TILES.T, TILES.D],
    [TILES.I, TILES.O, TILES.N, TILES.L, TILES.U, TILES.B],
];